steps:
  # Build backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/taskapp/backend:$COMMIT_SHA', './backend']

  # Build frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/taskapp/frontend:$COMMIT_SHA', './frontend']

  # Push backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/taskapp/backend:$COMMIT_SHA']

  # Push frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/taskapp/frontend:$COMMIT_SHA']

  # Deploy backend pe Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'taskapp-backend'
      - '--image=europe-west1-docker.pkg.dev/$PROJECT_ID/taskapp/backend:$COMMIT_SHA'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=3000'

  # Deploy frontend pe Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'taskapp-frontend'
      - '--image=europe-west1-docker.pkg.dev/$PROJECT_ID/taskapp/frontend:$COMMIT_SHA'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=80'

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/taskapp/backend:$COMMIT_SHA'
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/taskapp/frontend:$COMMIT_SHA'
